name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Make gradlew
        run: |
          wget https://services.gradle.org/distributions/gradle-8.0-bin.zip -P /tmp
          unzip /tmp/gradle-8.0-bin.zip -d /opt
          /opt/gradle-8.0/bin/gradle wrapper

      - name: Build APK
        run: ./gradlew assembleDebug
        
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: resolution-changer
          path: app/build/outputs/apk/debug/app-debug.apk
